// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wba.EE.DeMiddelaerBart.Domain.DataAccess;

namespace Wba.EE.DeMiddelaerBart.Domain.Migrations
{
    [DbContext(typeof(SiteContext))]
    partial class SiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wba.EE.DeMiddelaerBart.Domain.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("BMI")
                        .HasMaxLength(5);

                    b.Property<int>("HealthPoints")
                        .HasMaxLength(5);

                    b.Property<float>("Height")
                        .HasMaxLength(5);

                    b.Property<int>("Level")
                        .HasMaxLength(5);

                    b.Property<int>("Mana")
                        .HasMaxLength(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PokemonPictureUrl")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("Type");

                    b.Property<long?>("UserId");

                    b.Property<float>("Weight")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new { Id = 1, BMI = 8.2f, HealthPoints = 400, Height = 0.7f, Level = 28, Mana = 160, Name = "Bellsprout", PokemonPictureUrl = "/images/Pokemon/Bellsprout.svg", Type = 4, Weight = 4f },
                        new { Id = 2, BMI = 19.4f, HealthPoints = 300, Height = 0.6f, Level = 10, Mana = 160, Name = "Abra", PokemonPictureUrl = "/images/Pokemon/Abra.svg", Type = 5, Weight = 7f },
                        new { Id = 3, BMI = 14.1f, HealthPoints = 400, Height = 0.7f, Level = 29, Mana = 160, Name = "Bulbasaur", PokemonPictureUrl = "/images/Pokemon/Bulbasaur.svg", Type = 4, Weight = 6.9f },
                        new { Id = 4, BMI = 32.2f, HealthPoints = 400, Height = 0.3f, Level = 14, Mana = 160, Name = "Caterpie", PokemonPictureUrl = "/images/Pokemon/Caterpie.svg", Type = 4, Weight = 6.4f },
                        new { Id = 5, BMI = 23.6f, HealthPoints = 500, Height = 0.6f, Level = 14, Mana = 160, Name = "Charmander", PokemonPictureUrl = "/images/Pokemon/Charmander.svg", Type = 1, Weight = 18.7f },
                        new { Id = 6, BMI = 1f, HealthPoints = 400, Height = 1.8f, Level = 16, Mana = 160, Name = "Dratini", PokemonPictureUrl = "/images/Pokemon/Dratini.svg", Type = 2, Weight = 3.3f },
                        new { Id = 7, BMI = 72.2f, HealthPoints = 500, Height = 0.3f, Level = 24, Mana = 160, Name = "Eevee", PokemonPictureUrl = "/images/Pokemon/Eevee.svg", Type = 0, Weight = 6.5f },
                        new { Id = 8, BMI = 22f, HealthPoints = 600, Height = 0.5f, Level = 11, Mana = 160, Name = "Jigglypuff", PokemonPictureUrl = "/images/Pokemon/Jigglypuff.svg", Type = 0, Weight = 5.5f },
                        new { Id = 9, BMI = 26.3f, HealthPoints = 500, Height = 0.4f, Level = 18, Mana = 160, Name = "Meowth", PokemonPictureUrl = "/images/Pokemon/Meowth.svg", Type = 0, Weight = 4.2f },
                        new { Id = 10, BMI = 20f, HealthPoints = 400, Height = 0.3f, Level = 10, Mana = 160, Name = "Pidgey", PokemonPictureUrl = "/images/Pokemon/Pidgey.svg", Type = 0, Weight = 1.5f },
                        new { Id = 11, BMI = 37.5f, HealthPoints = 400, Height = 0.4f, Level = 18, Mana = 160, Name = "Pikachu", PokemonPictureUrl = "/images/Pokemon/Pikachu.svg", Type = 3, Weight = 6f },
                        new { Id = 12, BMI = 30.6f, HealthPoints = 500, Height = 0.8f, Level = 14, Mana = 160, Name = "Psyduck", PokemonPictureUrl = "/images/Pokemon/Psyduck.svg", Type = 2, Weight = 19.6f },
                        new { Id = 13, BMI = 38.9f, HealthPoints = 300, Height = 0.3f, Level = 23, Mana = 160, Name = "Rattata", PokemonPictureUrl = "/images/Pokemon/Rattata.svg", Type = 0, Weight = 3.5f },
                        new { Id = 14, BMI = 104.3f, HealthPoints = 900, Height = 2.1f, Level = 11, Mana = 160, Name = "Snorlax", PokemonPictureUrl = "/images/Pokemon/Snorlax.svg", Type = 0, Weight = 1014.1f },
                        new { Id = 15, BMI = 36f, HealthPoints = 400, Height = 0.5f, Level = 23, Mana = 160, Name = "Squirtle", PokemonPictureUrl = "/images/Pokemon/Squirtle.svg", Type = 2, Weight = 19.8f },
                        new { Id = 16, BMI = 30f, HealthPoints = 400, Height = 1f, Level = 28, Mana = 160, Name = "Venonat", PokemonPictureUrl = "/images/Pokemon/Venonat.svg", Type = 4, Weight = 30f },
                        new { Id = 17, BMI = 35.6f, HealthPoints = 400, Height = 0.3f, Level = 10, Mana = 160, Name = "Weedle", PokemonPictureUrl = "/images/Pokemon/Weedle.svg", Type = 4, Weight = 3.2f },
                        new { Id = 18, BMI = 25f, HealthPoints = 400, Height = 0.4f, Level = 18, Mana = 160, Name = "Mew", PokemonPictureUrl = "/images/Pokemon/Mew.svg", Type = 5, Weight = 4f },
                        new { Id = 19, BMI = 11.7f, HealthPoints = 400, Height = 0.8f, Level = 24, Mana = 160, Name = "Zubat", PokemonPictureUrl = "/images/Pokemon/Zubat.svg", Type = 4, Weight = 7.5f },
                        new { Id = 20, BMI = 44.4f, HealthPoints = 400, Height = 0.3f, Level = 28, Mana = 160, Name = "Ditto", PokemonPictureUrl = "/images/Pokemon/Ditto.svg", Type = 0, Weight = 4f },
                        new { Id = 21, BMI = 30f, HealthPoints = 500, Height = 2f, Level = 14, Mana = 160, Name = "Exeggutor", PokemonPictureUrl = "/images/Pokemon/Exeggutor.svg", Type = 4, Weight = 120f },
                        new { Id = 22, BMI = 26.4f, HealthPoints = 500, Height = 1.2f, Level = 19, Mana = 160, Name = "Sudowoodo", PokemonPictureUrl = "/images/Pokemon/Sudowoodo.svg", Type = 4, Weight = 38f },
                        new { Id = 23, BMI = 53.9f, HealthPoints = 450, Height = 0.8f, Level = 29, Mana = 160, Name = "Staryu", PokemonPictureUrl = "/images/Pokemon/Staryu.svg", Type = 2, Weight = 34.5f },
                        new { Id = 24, BMI = 66.7f, HealthPoints = 450, Height = 0.3f, Level = 14, Mana = 160, Name = "Magnemite", PokemonPictureUrl = "/images/Pokemon/Magnemite.svg", Type = 3, Weight = 6f },
                        new { Id = 25, BMI = 0.1f, HealthPoints = 450, Height = 1.3f, Level = 22, Mana = 160, Name = "Gastly", PokemonPictureUrl = "/images/Pokemon/Gastly.svg", Type = 5, Weight = 0.2f },
                        new { Id = 26, BMI = 13.4f, HealthPoints = 450, Height = 0.8f, Level = 17, Mana = 160, Name = "Gloom", PokemonPictureUrl = "/images/Pokemon/Gloom.svg", Type = 4, Weight = 8.6f },
                        new { Id = 27, BMI = 43.3f, HealthPoints = 450, Height = 0.7f, Level = 24, Mana = 160, Name = "Hoothoot", PokemonPictureUrl = "/images/Pokemon/Hoothoot.svg", Type = 0, Weight = 21.2f },
                        new { Id = 28, BMI = 53.1f, HealthPoints = 450, Height = 0.4f, Level = 13, Mana = 160, Name = "Marill", PokemonPictureUrl = "/images/Pokemon/Marill.svg", Type = 2, Weight = 8.5f },
                        new { Id = 29, BMI = 24.4f, HealthPoints = 550, Height = 0.6f, Level = 21, Mana = 160, Name = "Teddiursa", PokemonPictureUrl = "/images/Pokemon/Teddiursa.svg", Type = 0, Weight = 8.8f },
                        new { Id = 30, BMI = 41.6f, HealthPoints = 350, Height = 0.5f, Level = 22, Mana = 160, Name = "Voltorb", PokemonPictureUrl = "/images/Pokemon/Voltorb.svg", Type = 3, Weight = 10.4f },
                        new { Id = 31, BMI = 21.6f, HealthPoints = 350, Height = 0.5f, Level = 16, Mana = 160, Name = "Oddish", PokemonPictureUrl = "/images/Pokemon/Oddish.svg", Type = 4, Weight = 5.4f },
                        new { Id = 32, BMI = 23.4f, HealthPoints = 320, Height = 0.8f, Level = 24, Mana = 160, Name = "Duskull", PokemonPictureUrl = "/images/Pokemon/Duskull.svg", Type = 5, Weight = 15f },
                        new { Id = 33, BMI = 20f, HealthPoints = 600, Height = 1f, Level = 25, Mana = 160, Name = "Poliwhirl", PokemonPictureUrl = "/images/Pokemon/Poliwhirl.svg", Type = 2, Weight = 20f },
                        new { Id = 34, BMI = 20f, HealthPoints = 460, Height = 0.3f, Level = 29, Mana = 160, Name = "Sunkern", PokemonPictureUrl = "/images/Pokemon/Sunkern.svg", Type = 4, Weight = 1.8f },
                        new { Id = 35, BMI = 9.4f, HealthPoints = 320, Height = 0.8f, Level = 10, Mana = 160, Name = "Sentret", PokemonPictureUrl = "/images/Pokemon/Sentret.svg", Type = 0, Weight = 6f },
                        new { Id = 36, BMI = 10.8f, HealthPoints = 420, Height = 1f, Level = 17, Mana = 160, Name = "Ledyba", PokemonPictureUrl = "/images/Pokemon/Ledyba.svg", Type = 4, Weight = 10.8f },
                        new { Id = 37, BMI = 32.5f, HealthPoints = 600, Height = 2f, Level = 24, Mana = 160, Name = "Wailmer", PokemonPictureUrl = "/images/Pokemon/Wailmer.svg", Type = 2, Weight = 130f }
                    );
                });

            modelBuilder.Entity("Wba.EE.DeMiddelaerBart.Domain.Models.PokemonCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PokemonId");

                    b.Property<int?>("SkillOne");

                    b.Property<int?>("SkillTwo");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("UserId");

                    b.ToTable("Cards");

                    b.HasData(
                        new { Id = 1L, PokemonId = 17, SkillOne = 1, SkillTwo = 2, UserId = 1L },
                        new { Id = 2L, PokemonId = 23, SkillOne = 1, SkillTwo = 2, UserId = 1L },
                        new { Id = 3L, PokemonId = 21, SkillOne = 1, SkillTwo = 2, UserId = 1L },
                        new { Id = 4L, PokemonId = 31, SkillOne = 1, SkillTwo = 2, UserId = 2L },
                        new { Id = 5L, PokemonId = 13, SkillOne = 1, SkillTwo = 2, UserId = 2L },
                        new { Id = 6L, PokemonId = 16, SkillOne = 1, SkillTwo = 2, UserId = 2L },
                        new { Id = 7L, PokemonId = 23, SkillOne = 1, SkillTwo = 2, UserId = 3L },
                        new { Id = 8L, PokemonId = 13, SkillOne = 1, SkillTwo = 2, UserId = 4L },
                        new { Id = 9L, PokemonId = 16, SkillOne = 1, SkillTwo = 2, UserId = 4L },
                        new { Id = 10L, PokemonId = 32, SkillOne = 1, SkillTwo = 2, UserId = 5L },
                        new { Id = 11L, PokemonId = 25, SkillOne = 1, SkillTwo = 2, UserId = 6L },
                        new { Id = 12L, PokemonId = 32, SkillOne = 1, SkillTwo = 2, UserId = 6L },
                        new { Id = 13L, PokemonId = 10, SkillOne = 1, SkillTwo = 2, UserId = 7L },
                        new { Id = 14L, PokemonId = 6, SkillOne = 1, SkillTwo = 2, UserId = 7L },
                        new { Id = 15L, PokemonId = 30, SkillOne = 1, SkillTwo = 2, UserId = 7L },
                        new { Id = 16L, PokemonId = 3, SkillOne = 1, SkillTwo = 2, UserId = 8L },
                        new { Id = 17L, PokemonId = 2, SkillOne = 1, SkillTwo = 2, UserId = 8L },
                        new { Id = 18L, PokemonId = 10, SkillOne = 1, SkillTwo = 2, UserId = 8L },
                        new { Id = 19L, PokemonId = 20, SkillOne = 1, SkillTwo = 2, UserId = 8L },
                        new { Id = 20L, PokemonId = 17, SkillOne = 1, SkillTwo = 2, UserId = 8L },
                        new { Id = 21L, PokemonId = 12, SkillOne = 1, SkillTwo = 2, UserId = 9L },
                        new { Id = 22L, PokemonId = 29, SkillOne = 1, SkillTwo = 2, UserId = 10L },
                        new { Id = 23L, PokemonId = 20, SkillOne = 1, SkillTwo = 2, UserId = 10L },
                        new { Id = 24L, PokemonId = 33, SkillOne = 1, SkillTwo = 2, UserId = 11L },
                        new { Id = 25L, PokemonId = 8, SkillOne = 1, SkillTwo = 2, UserId = 11L },
                        new { Id = 26L, PokemonId = 2, SkillOne = 1, SkillTwo = 2, UserId = 11L },
                        new { Id = 27L, PokemonId = 28, SkillOne = 1, SkillTwo = 2, UserId = 11L },
                        new { Id = 28L, PokemonId = 28, SkillOne = 1, SkillTwo = 2, UserId = 12L },
                        new { Id = 29L, PokemonId = 22, SkillOne = 1, SkillTwo = 2, UserId = 12L },
                        new { Id = 30L, PokemonId = 35, SkillOne = 1, SkillTwo = 2, UserId = 13L },
                        new { Id = 31L, PokemonId = 34, SkillOne = 1, SkillTwo = 2, UserId = 13L },
                        new { Id = 32L, PokemonId = 13, SkillOne = 1, SkillTwo = 2, UserId = 13L },
                        new { Id = 33L, PokemonId = 7, SkillOne = 1, SkillTwo = 2, UserId = 14L },
                        new { Id = 34L, PokemonId = 9, SkillOne = 1, SkillTwo = 2, UserId = 14L },
                        new { Id = 35L, PokemonId = 10, SkillOne = 1, SkillTwo = 2, UserId = 15L },
                        new { Id = 36L, PokemonId = 21, SkillOne = 1, SkillTwo = 2, UserId = 15L },
                        new { Id = 37L, PokemonId = 22, SkillOne = 1, SkillTwo = 2, UserId = 15L },
                        new { Id = 38L, PokemonId = 9, SkillOne = 1, SkillTwo = 2, UserId = 15L }
                    );
                });

            modelBuilder.Entity("Wba.EE.DeMiddelaerBart.Domain.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Acc")
                        .HasMaxLength(5);

                    b.Property<int>("Dps")
                        .HasMaxLength(5);

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("ManaCost")
                        .HasMaxLength(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int?>("PokemonId");

                    b.Property<int>("Pp")
                        .HasMaxLength(5);

                    b.Property<int>("SkillType");

                    b.Property<int>("Turns")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("Skills");

                    b.HasData(
                        new { Id = 1, Acc = 100, Dps = 10, Effect = "May lower opponent's Speed by one stage.", ManaCost = 20, Name = "Constrict", Pp = 10, SkillType = 0, Turns = 1 },
                        new { Id = 2, Acc = 85, Dps = 15, Effect = "Hits up to 5 times in one turn.", ManaCost = 30, Name = "Barrage", Pp = 10, SkillType = 0, Turns = 5 },
                        new { Id = 3, Acc = 85, Dps = 15, Effect = "Traps opponent, damaging them for up to 5 turns.", ManaCost = 30, Name = "Bind", Pp = 10, SkillType = 0, Turns = 5 },
                        new { Id = 4, Acc = 85, Dps = 15, Effect = "Hits up to 5 times in one turn.", ManaCost = 30, Name = "DoubleSlap", Pp = 10, SkillType = 0, Turns = 5 },
                        new { Id = 5, Acc = 85, Dps = 15, Effect = "Hits up to 5 times in one turn.", ManaCost = 30, Name = "Fury Attack", Pp = 10, SkillType = 0, Turns = 5 },
                        new { Id = 6, Acc = 90, Dps = 15, Effect = "Traps opponent, damaging them up to 5 turns.", ManaCost = 30, Name = "Wrap", Pp = 10, SkillType = 0, Turns = 5 },
                        new { Id = 7, Acc = 85, Dps = 18, Effect = "Hits up to 5 times in one turn.", ManaCost = 35, Name = "Comet Punch", Pp = 10, SkillType = 0, Turns = 5 },
                        new { Id = 8, Acc = 90, Dps = 18, Effect = "Hits up to 5 times in one turn.", ManaCost = 35, Name = "Fury Swipes", Pp = 10, SkillType = 0, Turns = 5 },
                        new { Id = 9, Acc = 85, Dps = 20, Effect = "Raises user's Attack when hit.", ManaCost = 40, Name = "Rage", Pp = 10, SkillType = 0, Turns = 1 },
                        new { Id = 10, Acc = 80, Dps = 20, Effect = "Removes effects of trap moves.(NotWorking)", ManaCost = 40, Name = "Rapid Spin", Pp = 10, SkillType = 0, Turns = 1 },
                        new { Id = 11, Acc = 100, Dps = 20, Effect = "Hits up to 5 times in one turn.", ManaCost = 40, Name = "Spike Cannon", Pp = 10, SkillType = 0, Turns = 5 },
                        new { Id = 12, Acc = 100, Dps = 25, Effect = "Hits up to 5 times in one turn.", ManaCost = 50, Name = "Tail Slap", Pp = 10, SkillType = 0, Turns = 5 },
                        new { Id = 13, Acc = 100, Dps = 30, Effect = "Only hits if opponent uses Protect or Detect in the same turn.(NotWorking)", ManaCost = 60, Name = "Feint", Pp = 10, SkillType = 0, Turns = 1 },
                        new { Id = 14, Acc = 85, Dps = 35, Effect = "Hits twice in one turn.", ManaCost = 70, Name = "Double Hit", Pp = 10, SkillType = 0, Turns = 1 },
                        new { Id = 15, Acc = 100, Dps = 40, Effect = "Power increases each turn. (WorksHalf)", ManaCost = 80, Name = "Echoed Voice", Pp = 10, SkillType = 0, Turns = 1 },
                        new { Id = 16, Acc = 90, Dps = 40, Effect = "User attacks first, foe flinches. Only usable on first turn.(NotWorking)", ManaCost = 80, Name = "Fake Out", Pp = 10, SkillType = 0, Turns = 1 },
                        new { Id = 17, Acc = 100, Dps = 40, Effect = "Always leaves opponent with at least 1 HP.(NotWorking)", ManaCost = 80, Name = "False Swipe", Pp = 10, SkillType = 0, Turns = 1 },
                        new { Id = 18, Acc = 100, Dps = 40, Effect = "Always leaves opponent with at least 1 HP.(NotWorking)", ManaCost = 80, Name = "Hold Back", Pp = 10, SkillType = 0, Turns = 1 },
                        new { Id = 19, Acc = 100, Dps = 40, Effect = "A small amount of money is gained after the battle resolves.", ManaCost = 80, Name = "Pay Day", Pp = 10, SkillType = 0, Turns = 1 },
                        new { Id = 20, Acc = 100, Dps = 40, Effect = "Giving a Pounding MMMMMMMMMMmmmmmm", ManaCost = 80, Name = "Pound", Pp = 10, SkillType = 0, Turns = 1 },
                        new { Id = 21, Acc = 85, Dps = 15, Effect = "Traps opponent, damaging them for up to 10 turns.", ManaCost = 70, Name = "Fire Spin", Pp = 10, SkillType = 1, Turns = 10 },
                        new { Id = 22, Acc = 100, Dps = 60, Effect = "Destroys the target's held berry.(No barry in this game ;) )", ManaCost = 120, Name = "Incinerate", Pp = 10, SkillType = 1, Turns = 1 },
                        new { Id = 23, Acc = 100, Dps = 75, Effect = "May also injure nearby Pokémon.(Nop)", ManaCost = 140, Name = "Flame Burst", Pp = 10, SkillType = 1, Turns = 1 },
                        new { Id = 24, Acc = 100, Dps = 75, Effect = "May burn opponent", ManaCost = 150, Name = "FirePunch", Pp = 2, SkillType = 1, Turns = 1 },
                        new { Id = 25, Acc = 100, Dps = 40, Effect = "May burn opponent.", ManaCost = 80, Name = "Ember", Pp = 10, SkillType = 1, Turns = 1 },
                        new { Id = 26, Acc = 100, Dps = 60, Effect = "May burn opponent.", ManaCost = 120, Name = "FlameWheel", Pp = 10, SkillType = 1, Turns = 1 },
                        new { Id = 27, Acc = 100, Dps = 75, Effect = "Lowers opponent's Special Attack.(Nop)", ManaCost = 150, Name = "Mystical Fire", Pp = 2, SkillType = 1, Turns = 1 },
                        new { Id = 28, Acc = 100, Dps = 80, Effect = "May raise user's Special Attack.(Nop)", ManaCost = 160, Name = "FieryDance", Pp = 2, SkillType = 1, Turns = 1 },
                        new { Id = 29, Acc = 100, Dps = 50, Effect = "Raises user's Speed.", ManaCost = 100, Name = "Flame Charge", Pp = 10, SkillType = 1, Turns = 1 },
                        new { Id = 30, Acc = 100, Dps = 65, Effect = "May cause flinching and/or burn opponent.", ManaCost = 130, Name = "Fire Fang", Pp = 10, SkillType = 1, Turns = 1 },
                        new { Id = 31, Acc = 100, Dps = 15, Effect = "Hits up to 5 times in one turn.", ManaCost = 30, Name = "Water Shuriken", Pp = 20, SkillType = 2, Turns = 5 },
                        new { Id = 32, Acc = 85, Dps = 40, Effect = "Traps opponent, damaging them for up to 5 turns.", ManaCost = 80, Name = "Bubble", Pp = 20, SkillType = 2, Turns = 5 },
                        new { Id = 33, Acc = 100, Dps = 60, Effect = "May confuse opponent.", ManaCost = 120, Name = "Water Pulse", Pp = 2, SkillType = 2, Turns = 1 },
                        new { Id = 34, Acc = 100, Dps = 65, Effect = "May lower opponent's Speed.", ManaCost = 130, Name = "Bubble Beam", Pp = 2, SkillType = 2, Turns = 1 },
                        new { Id = 35, Acc = 85, Dps = 35, Effect = "Traps opponent, damaging them for up to 5 turns.", ManaCost = 70, Name = "Clamp", Pp = 10, SkillType = 2, Turns = 5 },
                        new { Id = 36, Acc = 100, Dps = 40, Effect = "Water Gun deals damage with no additional effect.", ManaCost = 80, Name = "Water Gun", Pp = 30, SkillType = 2, Turns = 1 },
                        new { Id = 37, Acc = 100, Dps = 65, Effect = "May lower opponent's Accuracy.", ManaCost = 130, Name = "Octazooka", Pp = 2, SkillType = 2, Turns = 1 },
                        new { Id = 38, Acc = 100, Dps = 75, Effect = "Power doubles if opponent's HP is less than 50%", ManaCost = 150, Name = "Brine", Pp = 2, SkillType = 2, Turns = 1 },
                        new { Id = 39, Acc = 85, Dps = 35, Effect = "Traps opponent, damaging them for up to 5 turns.", ManaCost = 70, Name = "Whirlpool", Pp = 15, SkillType = 2, Turns = 5 },
                        new { Id = 40, Acc = 100, Dps = 40, Effect = "User attacks first.", ManaCost = 80, Name = "Aqua Jet", Pp = 10, SkillType = 2, Turns = 1 },
                        new { Id = 41, Acc = 100, Dps = 15, Effect = "Paralyzes opponent.", ManaCost = 30, Name = "Nuzzle", Pp = 20, SkillType = 3, Turns = 1 },
                        new { Id = 42, Acc = 85, Dps = 40, Effect = "High critical-hit ratio.(Nop)", ManaCost = 80, Name = "Zippy Zap", Pp = 20, SkillType = 3, Turns = 1 },
                        new { Id = 43, Acc = 100, Dps = 60, Effect = "User recovers half the HP inflicted on opponent.", ManaCost = 120, Name = "Parabolic Charge", Pp = 2, SkillType = 3, Turns = 1 },
                        new { Id = 44, Acc = 100, Dps = 65, Effect = "May cause flinching and/or paralyze opponent.", ManaCost = 130, Name = "Thunder Fang", Pp = 2, SkillType = 3, Turns = 1 },
                        new { Id = 45, Acc = 85, Dps = 35, Effect = "May paralyze opponent.", ManaCost = 70, Name = "Thunder Shock", Pp = 10, SkillType = 3, Turns = 1 },
                        new { Id = 46, Acc = 100, Dps = 40, Effect = "Lowers opponent's Speed.", ManaCost = 80, Name = "Electroweb", Pp = 30, SkillType = 3, Turns = 1 },
                        new { Id = 47, Acc = 100, Dps = 65, Effect = "May paralyze opponent.", ManaCost = 130, Name = "Spark", Pp = 2, SkillType = 3, Turns = 1 },
                        new { Id = 48, Acc = 100, Dps = 75, Effect = "User must switch out after attacking.(Nop)", ManaCost = 150, Name = "Volt Switch", Pp = 2, SkillType = 3, Turns = 1 },
                        new { Id = 49, Acc = 85, Dps = 35, Effect = "May raise user's Special Attack.", ManaCost = 70, Name = "Charge Beam", Pp = 15, SkillType = 3, Turns = 1 },
                        new { Id = 50, Acc = 100, Dps = 40, Effect = "Ignores Accuracy and Evasiveness.", ManaCost = 80, Name = "Shock Wave", Pp = 10, SkillType = 3, Turns = 1 },
                        new { Id = 51, Acc = 100, Dps = 75, Effect = "May paralyze opponent.", ManaCost = 150, Name = "Thunder Punch", Pp = 2, SkillType = 3, Turns = 1 },
                        new { Id = 52, Acc = 100, Dps = 75, Effect = "May paralyze opponent.", ManaCost = 150, Name = "Discharge", Pp = 2, SkillType = 3, Turns = 1 },
                        new { Id = 53, Acc = 100, Dps = 75, Effect = "Overdrive has no added effects.(Nop)", ManaCost = 150, Name = "Overdrive", Pp = 2, SkillType = 3, Turns = 1 },
                        new { Id = 54, Acc = 100, Dps = 15, Effect = "User recovers half the HP inflicted on opponent.", ManaCost = 30, Name = "Absorb", Pp = 20, SkillType = 4, Turns = 1 },
                        new { Id = 55, Acc = 100, Dps = 40, Effect = "Strikes opponent with leaves.", ManaCost = 80, Name = "Leafage", Pp = 30, SkillType = 4, Turns = 1 },
                        new { Id = 56, Acc = 100, Dps = 65, Effect = "High critical hit ratio.", ManaCost = 130, Name = "Razor Leaf", Pp = 2, SkillType = 4, Turns = 1 },
                        new { Id = 57, Acc = 100, Dps = 75, Effect = "May lower opponent's Accuracy.", ManaCost = 150, Name = "Leaf Tornado", Pp = 2, SkillType = 4, Turns = 1 },
                        new { Id = 58, Acc = 85, Dps = 35, Effect = "Hits up to 5 times in one turn.", ManaCost = 70, Name = "Bullet Seed", Pp = 10, SkillType = 4, Turns = 5 },
                        new { Id = 59, Acc = 100, Dps = 40, Effect = "User recovers half the HP inflicted on opponent.", ManaCost = 80, Name = "Mega Drain", Pp = 10, SkillType = 4, Turns = 1 },
                        new { Id = 60, Acc = 100, Dps = 65, Effect = "Ignores Accuracy and Evasiveness", ManaCost = 130, Name = "Magical Leaf", Pp = 2, SkillType = 4, Turns = 1 },
                        new { Id = 61, Acc = 100, Dps = 75, Effect = "Lowers opponent's Attack.", ManaCost = 150, Name = "Trop Kick", Pp = 2, SkillType = 4, Turns = 1 },
                        new { Id = 62, Acc = 85, Dps = 35, Effect = "Snares the target in a snap trap for four to 5 turns.", ManaCost = 70, Name = "Snap Trap", Pp = 15, SkillType = 4, Turns = 5 },
                        new { Id = 63, Acc = 100, Dps = 60, Effect = " Wips vine's.", ManaCost = 120, Name = "Vine Whip", Pp = 2, SkillType = 4, Turns = 1 },
                        new { Id = 64, Acc = 100, Dps = 75, Effect = "May cause flinching.(Wut ?)", ManaCost = 150, Name = "Needle Arm", Pp = 2, SkillType = 4, Turns = 1 },
                        new { Id = 65, Acc = 100, Dps = 75, Effect = "User recovers half the HP inflicted on opponent.", ManaCost = 150, Name = "Giga Drain", Pp = 2, SkillType = 4, Turns = 1 },
                        new { Id = 66, Acc = 85, Dps = 40, Effect = "Poke's.", ManaCost = 80, Name = "Branch Poke", Pp = 20, SkillType = 4, Turns = 1 },
                        new { Id = 67, Acc = 100, Dps = 15, Effect = "Power increases when user's stats have been raised.(Nop)", ManaCost = 30, Name = "Stored Power", Pp = 20, SkillType = 5, Turns = 1 },
                        new { Id = 68, Acc = 100, Dps = 40, Effect = "High critical hit ratio.", ManaCost = 80, Name = "Psycho Cut", Pp = 30, SkillType = 5, Turns = 1 },
                        new { Id = 69, Acc = 100, Dps = 65, Effect = "May cause flinching.(Nop)", ManaCost = 130, Name = "ZenHeadbutt", Pp = 2, SkillType = 5, Turns = 1 },
                        new { Id = 70, Acc = 85, Dps = 35, Effect = "May confuse opponent.", ManaCost = 70, Name = "Confusion", Pp = 10, SkillType = 5, Turns = 1 },
                        new { Id = 71, Acc = 100, Dps = 40, Effect = "May lower opponent's Special Attack.(Nop)", ManaCost = 80, Name = "Mist Ball", Pp = 10, SkillType = 5, Turns = 1 },
                        new { Id = 72, Acc = 100, Dps = 75, Effect = "Can strike through Protect/Detect.(Nop)", ManaCost = 150, Name = "HyperspaceHole", Pp = 2, SkillType = 5, Turns = 1 },
                        new { Id = 73, Acc = 100, Dps = 75, Effect = "May cause flinching.(Nop)", ManaCost = 150, Name = "Extrasensory", Pp = 2, SkillType = 5, Turns = 1 },
                        new { Id = 74, Acc = 85, Dps = 35, Effect = "May cause flinching.(Nop)", ManaCost = 70, Name = "Heart Stamp", Pp = 15, SkillType = 5, Turns = 1 },
                        new { Id = 75, Acc = 100, Dps = 60, Effect = "May lower opponent's Special Defense.(Nop)", ManaCost = 120, Name = "Luster Purge", Pp = 2, SkillType = 5, Turns = 1 },
                        new { Id = 76, Acc = 100, Dps = 65, Effect = "Inflicts damage based on the target's Defense, not Special Defense.(Nop)", ManaCost = 130, Name = "Psyshock", Pp = 2, SkillType = 5, Turns = 1 },
                        new { Id = 77, Acc = 85, Dps = 40, Effect = "May confuse opponent.", ManaCost = 80, Name = "Psybeam", Pp = 20, SkillType = 5, Turns = 1 }
                    );
                });

            modelBuilder.Entity("Wba.EE.DeMiddelaerBart.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio")
                        .HasMaxLength(999);

                    b.Property<string>("Country")
                        .HasMaxLength(20);

                    b.Property<DateTime>("DayOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<int>("GenderId");

                    b.Property<int?>("HighScore");

                    b.Property<int?>("IndexOfAvatarSelectit");

                    b.Property<int?>("IndexOfTeamSelectit");

                    b.Property<string>("Name")
                        .HasMaxLength(15);

                    b.Property<string>("Password");

                    b.Property<string>("PasswordSalt");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20);

                    b.Property<int>("TypeOfUser");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                    that you can now copy and paste your fancy text in the comments section of funny cat videos,
                    but perhaps you're wondering how it's even possible to
                    change the font of your text? Is it some sort of hack? 
                    Are you copying and pasting an actual font?

                    Well, the answer is actually no - rather than generating fancy fonts, this converter creates fancy 
                    symbols. The explanation starts with unicode; an industry standard which creates the specification for 
                    thousands of different symbols and characters. All the characters that you see on your electronic devices,
                    and printed in books, are likely specified by the unicode standard.", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 5, HighScore = 1024, IndexOfAvatarSelectit = 1, IndexOfTeamSelectit = 1, Name = "a", Password = "Xi+EHrnw3grShXW3TJqMo9t6j0poTd/cHuAVM3IraEQ=", PasswordSalt = "xn2HEry2reJEryEULLa9", PhoneNumber = "0499855224", TypeOfUser = 0 },
                        new { Id = 2L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 1, HighScore = 236, IndexOfAvatarSelectit = 8, IndexOfTeamSelectit = 2, Name = "Seed User 2", Password = "2ns8HDhUybSqSvnLU+rQ/V+zG7SL1pS4BbgQf9NlyG4=", PasswordSalt = "NyWcBF0ditaJx6H9nkGT", PhoneNumber = "049985522", TypeOfUser = 1 },
                        new { Id = 3L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 3, HighScore = 488, IndexOfAvatarSelectit = 4, IndexOfTeamSelectit = 1, Name = "Seed User 3", Password = "s//wmR2wTXtxnuw/MP9m58YwAn3hrXAs2nvxCY80sHI=", PasswordSalt = "AqE9namcod5f8sNadtY8", PhoneNumber = "049985523", TypeOfUser = 1 },
                        new { Id = 4L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 3, HighScore = 314, IndexOfAvatarSelectit = 7, IndexOfTeamSelectit = 3, Name = "Seed User 4", Password = "4IdVsCzPkxUwy/vBsJWZwbyqGPb0Uc9oIMb6sesWqM0=", PasswordSalt = "+gZUZA6DNxmvBJR1Aqjb", PhoneNumber = "049985524", TypeOfUser = 1 },
                        new { Id = 5L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 2, HighScore = 512, IndexOfAvatarSelectit = 4, IndexOfTeamSelectit = 2, Name = "Seed User 5", Password = "m0ID5xyMWNinh+fbJXqi0XjNjl+9s+mEKO0/qHeAkTc=", PasswordSalt = "WZFh0b14kbpbE2b4SUoK", PhoneNumber = "049985525", TypeOfUser = 1 },
                        new { Id = 6L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 2, HighScore = 593, IndexOfAvatarSelectit = 12, IndexOfTeamSelectit = 1, Name = "Seed User 6", Password = "ACdtS3YHZwtB5IfTZSShHC+bwUsZMtB87ytbTs8d/gc=", PasswordSalt = "pC9SaN3poQ6UCcrITqeG", PhoneNumber = "049985526", TypeOfUser = 1 },
                        new { Id = 7L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 2, HighScore = 962, IndexOfAvatarSelectit = 4, IndexOfTeamSelectit = 3, Name = "Seed User 7", Password = "b0YXZ1A/9ezv/h3iGVOqKR1ZETNirVyUYcBzJLdrSCc=", PasswordSalt = "Q3G6YkF8m+auo6HenHJ8", PhoneNumber = "049985527", TypeOfUser = 1 },
                        new { Id = 8L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 2, HighScore = 801, IndexOfAvatarSelectit = 10, IndexOfTeamSelectit = 3, Name = "Seed User 8", Password = "tfIKf4u1eFjf5YcNgj5PiT4hbeKAVutQ/dZwhu3NV0Q=", PasswordSalt = "oaQHEqVkzMDryDZ8RngT", PhoneNumber = "049985528", TypeOfUser = 1 },
                        new { Id = 9L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 3, HighScore = 428, IndexOfAvatarSelectit = 2, IndexOfTeamSelectit = 1, Name = "Seed User 9", Password = "sia/42loKPTlZpGIzjx+Nz59plYz/KJPfx+hZ3UhT4E=", PasswordSalt = "iq5qk4/Pw9YOnvb+mCjU", PhoneNumber = "049985529", TypeOfUser = 1 },
                        new { Id = 10L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 4, HighScore = 75, IndexOfAvatarSelectit = 5, IndexOfTeamSelectit = 1, Name = "Seed User 10", Password = "mOg1SbSporCao1mWUPxhEAPcKSY+psg3SsnmaR5lR8E=", PasswordSalt = "Af0DNt/p2Dyou4vecQHz", PhoneNumber = "0499855210", TypeOfUser = 1 },
                        new { Id = 11L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 4, HighScore = 914, IndexOfAvatarSelectit = 1, IndexOfTeamSelectit = 1, Name = "Seed User 11", Password = "EHVIfrKKwm+pzPKBrkBGdv1cy3pHegdCbBhy5Qe0Huw=", PasswordSalt = "9WghGPyLvdvukHoyTbPO", PhoneNumber = "0499855211", TypeOfUser = 1 },
                        new { Id = 12L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 4, HighScore = 519, IndexOfAvatarSelectit = 11, IndexOfTeamSelectit = 3, Name = "Seed User 12", Password = "gcjfw2TqkKtOBH7q8EYG447Jamp0LJKR10hmitMq8ns=", PasswordSalt = "31VUzO7ltpl+N0KnTfgr", PhoneNumber = "0499855212", TypeOfUser = 1 },
                        new { Id = 13L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 2, HighScore = 891, IndexOfAvatarSelectit = 10, IndexOfTeamSelectit = 1, Name = "Seed User 13", Password = "lZQXjhWVqW7423vzKBcoX7NDnvFoF4XKmR+8yk7bP2Y=", PasswordSalt = "j51ogS9D759ncLfK/mdw", PhoneNumber = "0499855213", TypeOfUser = 1 },
                        new { Id = 14L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 4, HighScore = 638, IndexOfAvatarSelectit = 1, IndexOfTeamSelectit = 2, Name = "Seed User 14", Password = "/WruwvwYC1z0Zq8K4Sr4Wo4M9xldHhNMrGU9LkzD/Lk=", PasswordSalt = "PC+Bw9gJB9ZYjkT46Iaw", PhoneNumber = "0499855214", TypeOfUser = 1 },
                        new { Id = 15L, Bio = @"So perhaps, you've generated some fancy text, and you're content
                                that you can now copy and paste your fancy text in the comments section of funny cat videos,
                                but perhaps you're wondering how it's even possible to
                                change the font of your text? Is it some sort of hack? 
                                Are you copying and pasting an actual font?
                    ", Country = "Belgium", DayOfBirth = new DateTime(1920, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "OtenToten@Tontoonstelling.com", GenderId = 3, HighScore = 634, IndexOfAvatarSelectit = 3, IndexOfTeamSelectit = 3, Name = "Seed User 15", Password = "vqOlnt52eXuHBbeBrMcr0UKWKh/fzMxL6PKKAq3scnI=", PasswordSalt = "mNPDFM2HShweC5WObyrL", PhoneNumber = "0499855215", TypeOfUser = 1 }
                    );
                });

            modelBuilder.Entity("Wba.EE.DeMiddelaerBart.Domain.Models.Pokemon", b =>
                {
                    b.HasOne("Wba.EE.DeMiddelaerBart.Domain.Models.User")
                        .WithMany("PlayDeck")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Wba.EE.DeMiddelaerBart.Domain.Models.PokemonCard", b =>
                {
                    b.HasOne("Wba.EE.DeMiddelaerBart.Domain.Models.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId");

                    b.HasOne("Wba.EE.DeMiddelaerBart.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Wba.EE.DeMiddelaerBart.Domain.Models.Skill", b =>
                {
                    b.HasOne("Wba.EE.DeMiddelaerBart.Domain.Models.Pokemon")
                        .WithMany("ThisPokemonsSkills")
                        .HasForeignKey("PokemonId");
                });
#pragma warning restore 612, 618
        }
    }
}
